<?php

namespace Ibantest\WooCommerce;

use Digitick\Sepa\PaymentInformation;
use Digitick\Sepa\TransferFile\Factory\TransferFileFacadeFactory;
use Ibantest\WooCommerce\Orders\DirectDebitOrderMeta;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class SepaExport {
	private string $last_error = '';

	public function __construct( private Plugin $plugin ) {}

	public function init(): void {
		add_action( 'admin_post_ibantest_export_sepa', [ $this, 'download' ] );
	}

	public function download(): void {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_die( esc_html__( 'You are not allowed to export SEPA files.', 'ibantest-for-woocommerce' ), 403 );
		}

		$order_id = isset( $_GET['order_id'] ) ? absint( $_GET['order_id'] ) : 0;
		if ( ! $order_id || ! check_admin_referer( 'ibantest_export_sepa_' . $order_id ) ) {
			wp_die( esc_html__( 'Invalid SEPA export request.', 'ibantest-for-woocommerce' ), 403 );
		}

		$order = wc_get_order( $order_id );
		if ( ! $order || Plugin::GATEWAY_ID !== $order->get_payment_method() ) {
			wp_die( esc_html__( 'Order is not payable by IBANTEST SEPA Direct Debit.', 'ibantest-for-woocommerce' ), 404 );
		}

		$xml = $this->build_xml( $order );
		if ( '' === $xml ) {
			wp_die( esc_html( $this->last_error ?: __( 'SEPA XML could not be generated.', 'ibantest-for-woocommerce' ) ), 500 );
		}

		$filename = 'SEPA-Export-order-' . $order->get_id() . '.xml';

		nocache_headers();
		header( 'Content-Description: File Transfer' );
		header( 'Content-Disposition: attachment; filename="' . sanitize_file_name( $filename ) . '"' );
		header( 'Content-Type: text/xml; charset=' . get_option( 'blog_charset' ), true );

		echo $xml; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- XML generated by the SEPA library.
		exit;
	}

	public function build_xml( \WC_Order $order ): string {
		$this->last_error = '';
		$settings = $this->plugin->settings();

		foreach ( [ 'creditor_agent_bic', 'creditor_name', 'sepa_xml_format', 'creditor_account_holder', 'creditor_account_iban', 'creditor_id' ] as $required ) {
			if ( empty( $settings[ $required ] ) ) {
				return $this->fail( sprintf( 'Missing SEPA creditor setting: %s', $required ) );
			}
		}

		try {
			$direct_debit = TransferFileFacadeFactory::createDirectDebit(
				sanitize_key( (string) $settings['creditor_agent_bic'] ) . '-' . gmdate( 'Ymd-His' ),
				(string) $settings['creditor_name'],
				(string) $settings['sepa_xml_format']
			);

			$payment_name = 'PMT-ID-' . gmdate( 'Ymd-His' );
			$direct_debit->addPaymentInfo(
				$payment_name,
				[
					'id'                  => $payment_name,
					'dueDate'             => new \DateTime( 'now' ),
					'creditorName'        => (string) $settings['creditor_account_holder'],
					'creditorAccountIBAN' => (string) $settings['creditor_account_iban'],
					'creditorAgentBIC'    => (string) $settings['creditor_agent_bic'],
					'creditorId'          => (string) $settings['creditor_id'],
					'seqType'             => PaymentInformation::S_ONEOFF,
					'localInstrumentCode' => 'CORE',
				]
			);

			$debtor_iban = $this->plugin->encryption()->decrypt( (string) $order->get_meta( DirectDebitOrderMeta::META_IBAN ) );
			$debtor_name = $this->plugin->encryption()->decrypt( (string) $order->get_meta( DirectDebitOrderMeta::META_HOLDER ) );
			$mandate_id  = (string) $order->get_meta( DirectDebitOrderMeta::META_MANDATE_ID );

			$this->assert_not_empty( $debtor_iban, __( 'SEPA XML could not be generated because the debtor IBAN is missing or cannot be decrypted.', 'ibantest-for-woocommerce' ) );
			$this->assert_not_empty( $debtor_name, __( 'SEPA XML could not be generated because the debtor name is missing or cannot be decrypted.', 'ibantest-for-woocommerce' ) );
			$this->assert_not_empty( $mandate_id, __( 'SEPA XML could not be generated because the debtor mandate reference is missing.', 'ibantest-for-woocommerce' ) );

			$mandate_date = (int) $order->get_meta( DirectDebitOrderMeta::META_MANDATE_DATE );
			$transfer     = [
				'amount'                => $this->amount_in_cents( (string) $order->get_total() ),
				'debtorIban'            => $debtor_iban,
				'debtorName'            => $debtor_name,
				'debtorMandate'         => $mandate_id,
				'debtorMandateSignDate' => new \DateTime( gmdate( 'Y-m-d', $mandate_date ?: time() ) ),
				'creditorReference'     => '',
				'remittanceInformation' => sprintf(
					/* translators: %s: order number. */
					__( 'Order %s', 'ibantest-for-woocommerce' ),
					$order->get_order_number()
				),
			];

			$debtor_bic = $this->plugin->encryption()->decrypt( (string) $order->get_meta( DirectDebitOrderMeta::META_BIC ) );
			$transfer['debtorBic'] = $debtor_bic;

			$direct_debit->addTransfer( $payment_name, $transfer );

			return $direct_debit->asXML();
		} catch ( \Throwable $e ) {
			return $this->fail( $e->getMessage() ?: __( 'SEPA XML could not be generated.', 'ibantest-for-woocommerce' ) );
		}
	}

	public function last_error(): string {
		return $this->last_error;
	}

	private function assert_not_empty( string $value, string $message ): void {
		if ( '' === trim( $value ) ) {
			throw new \RuntimeException( $message );
		}
	}

	private function amount_in_cents( string $amount ): int {
		$normalized = str_replace( ',', '.', trim( $amount ) );
		if ( ! preg_match( '/^(\d+)(?:\.(\d{1,2}))?$/', $normalized, $matches ) ) {
			throw new \RuntimeException( __( 'SEPA XML could not be generated because the order total is invalid.', 'ibantest-for-woocommerce' ) );
		}

		$major = ltrim( $matches[1], '0' );
		$minor = str_pad( $matches[2] ?? '', 2, '0' );

		return (int) ( ( '' === $major ? '0' : $major ) . $minor );
	}

	private function fail( string $message ): string {
		$this->last_error = $message;
		return '';
	}
}
